server:
  port: 8080
  
spring:
  cloud:
    gateway:
      default-filters:
        - name: CountFilter
      routes:
        - id: movieRoute
          uri: http://localhost:8081/
          predicates:
            - Path=/movies/**
          filters:
            - AddRequestHeader=movie-request-header, testing-request-headers
            - AddResponseHeader=movie-response-header, testing-response-headers
        - id: catalogRoute
          uri: http://localhost:8082/
          predicates:
            - Path=/catalogs/**
